name: 1-Hour Karing Reserve Mobile Sync

on:
  schedule:
    - cron: '15 * * * *' # Раз в час на 15-й минуте
  workflow_dispatch: # Кнопка для ручного запуска

permissions:
  contents: write # Даем полные права на перезапись репозитория!

jobs:
  sync-sort-reserve:
    runs-on: ubuntu-latest
    steps:
      - name: Открываем твой репозиторий
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Скачиваем резервные прокси у igareck
        run: |
          curl -s "https://githubusercontent.com" -o raw_reserve.txt || touch raw_reserve.txt

      - name: Быстрая очистка и подготовка списка
        run: |
          touch temp_raw.txt
          cat raw_reserve.txt > temp_raw.txt 2>/dev/null || true
          cat temp_raw.txt | grep -E '^([a-zA-Z0-9_-]+)://' | sort -u > karing_reserve_final.txt || touch karing_reserve_final.txt
          echo "Резервный список успешно собран и очищен!"

      - name: Жесткое принудительное сохранение файлов на сайт
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add karing_reserve_final.txt
          # МЫ УБРАЛИ ВСЕ ТЕГИ ТИПА [skip ci], ЧТОБЫ СНЯТЬ БЛОКИРОВКУ СЕТИ!
          git commit -m "Финальный чистый пробив резервных прокси Shadowsocks" --allow-empty
          git pull origin main --rebase
          git push origin main
